app:
  # Log leverl: debug, info, warn, error
  logging: "debug"

  # HTTP address and port to listen to
  address: ":8080"

  # Storage: slice,postgres
  storage: "postgres"


postgres:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: password
